name = "Skylight"
uuid = "4e57a7cc-3de9-485c-8eb7-83ba6280373b"
authors = ["Joaquin Pelle", "Oscar Reula", "Federico Carrasco", "Carlos Bederian"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
