include("cache.jl")
include("views.jl")
include("finalpositions.jl")
include("normalization.jl")
include("redshift.jl")
include("intensities.jl")
include("intensities_pinhole.jl")
include("lineemission.jl")

energies_quotients(initial_data, output_data, configurations::VacuumOTEConfigurations; kwargs...) = energies_quotients(initial_data, output_data, configurations, configurations.camera; kwargs...)
observed_bolometric_intensities(initial_data, output_data, configurations::VacuumOTEConfigurations; kwargs...) = observed_bolometric_intensities(initial_data, output_data, configurations, configurations.camera; kwargs...)
# observed_specific_intensities(initial_data, output_data, configurations::VacuumOTEConfigurations, energies; kwargs...) = observed_specific_intensities(initial_data, output_data, configurations, configurations.camera, energies; kwargs...)